LEGAL_DISCLAIMER_HEADER = (
    "NOTICE: This decision recommendation is generated by an automated multi-agent claims adjudication system "
    "subject to regulatory oversight under applicable insurance statutes and state department of insurance guidelines. "
    "All decisions subject to manual review or appeal retain human adjudicator authority."
)

CLAIMANT_EXPLANATION_DISCLAIMER = (
    "This explanation provides an overview of your claim decision based on your policy terms. "
    "If you disagree with this finding, you have the right to request a formal administrative review or submit additional medical documentation."
)
